## FULL Installation ################################
##conda create -n LONGSTITCH_env
##conda activate LONGSTITCH_env
##conda install -c bioconda -c conda-forge longstitch
#####################################################

#SBATCH -J LongSt
#SBATCH -o /scratch/ddepanis/stdout/%x.%j.out
#SBATCH -e /scratch/ddepanis/stderr/%x.%j.err

#SBATCH --mail-type=ALL
#SBATCH --mail-user=..@...

#SBATCH --partition=begendiv,main
#SBATCH --qos=standard
#SBATCH --cpus-per-task=8
#SBATCH --mem=24G
#SBATCH --time=48:00:00

export PATH=~/Software/anaconda3/bin:$PATH
source activate LONGSTITCH_env


##########################################################################
# Only modify these variables:
ASM="../purge_dups/PE/p1/purged_33_99.fa"
ASM_NAME=$(basename $ASM .fa)
LONG_READS="../intermediates/demit/minion_demit.fq"
READS_NAME=$(basename $LONG_READS .fq)
GENOME_SIZE="1200000000"
LONGST_DIR="../intermediates/longstitch"
##########################################################################

## For ONT reads
mkdir -p $LONGST_DIR
cd $LONGST_DIR

ln -s $ASM $ASM_NAME\.fa
cp $LONG_READS .
pigz -p 8 $READS_NAME\.fq

longstitch run draft=$ASM_NAME reads=$READS_NAME G=$GENOME_SIZE

rm $READS_NAME\.fq.gz

