#!/bin/bash

## Full installation ######################################################
##conda create -n MERQURY_env -c conda-forge -c bioconda merqury openjdk=11
##cd ../Software
##git clone https://github.com/tbenavi1/genomescope2.0.git
##cd genomescope2.0/
##echo "R_LIBS=~/R_libs/" >> ~/.Renviron
##Rscript install.R
###########################################################################

#SBATCH -J meryl
#SBATCH -o ../stdout/meryl.%j.out
#SBATCH -e ../stderr/meryl.%j.err
##SBATCH -D 

#SBATCH --mail-type=ALL
#SBATCH --mail-user=..@..

#SBATCH --partition=begendiv,main
#SBATCH --qos=standard
#SBATCH --cpus-per-task=32
#SBATCH --mem=64G
#SBATCH --time=24:00:00

export PATH=../Software/anaconda3/bin:$PATH
source activate MERQURY_env

GENOMESCOPE2="/scratch/ddepanis/Software/genomescope2.0/genomescope.R"


## Only change this: ############################################
FQ_DIR="../Condor_project/Pehuel/intermediates/trimming"
OUT_DIR="../Condor_project/Pehuel/evaluation/meryl"
GENOMESCOPE_OUT_DIR="../Condor_project/Pehuel/evaluation/genomescope"
FINAL_NAME="WGS_trimmed"
#################################################################


# build meryl database for each file
mkdir -p $OUT_DIR
cd $OUT_DIR
for i in $(ls $FQ_DIR/illuminaPE_*.fq)
do
        NAME=$(basename $i .fastq.gz)
        meryl k=21 memory=64 threads=32 count $i output $NAME\.meryl
done

# merge all databases
meryl k=21 memory=64 threads=32 union-sum output $FINAL_NAME\.meryl *.meryl

# get histogram for genomescope
meryl histogram $FINAL_NAME\.meryl | sed 's/\t/ /g' > $FINAL_NAME\.hist

# run genomescope
mkdir -p $GENOMESCOPE_OUT_DIR
Rscript $GENOMESCOPE2 -i $OUT_DIR/$FINAL_NAME\.hist -o $GENOMESCOPE_OUT_DIR -k 21 --fitted_hist

# get useful values
cd $GENOMESCOPE_OUT_DIR

VAR="$(grep -n "Genome Haploid Length" summary.txt | cut -f1 -d:)"
sed -n $VAR\p summary.txt | sed -e 's/  \+/\t/g' | cut -f3 | sed -e 's/,//g' | sed -e 's/ bp//g' > Estimated_genome_size

VAR="$(grep -n "kmercov " model.txt | cut -f1 -d:)"
KCOV="$(printf "%.2f\n" $(sed -n $VAR\p model.txt | sed -e 's/ \+/\t/g' | cut -f2))"
printf "%.0f\n" $(echo "$KCOV * 1.5" | bc) > Transition_parameter
printf "%.0f\n" $(echo ""$(cat Transition_parameter)" * 3" | bc) > Maximum_depth
